name: Release Go Binaries

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CMD_PATH: ./cmd/skillshare-downloader

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: windows
          - goarch: arm64
            goos: windows
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}

      - uses: wangyoucao577/go-release-action@v1.38
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "${{ env.CMD_PATH }}"
          build_flags: -v
          ldflags: -X "main.appVersion=${{ env.APP_VERSION }}" -X "main.buildTime=${{ env.BUILD_TIME }}" -X main.gitCommit=${{ github.sha }} -X main.gitRef=${{ github.ref }}
          goversion: "https://dl.google.com/go/go1.20.3.linux-amd64.tar.gz"
          extra_files: LICENSE README.md
